### ISSUE TITLE
Could you please share your parsed data or codes for preprocessing?

### ISSUE THREAD

**Issue by eefaan** [guxd/DialogBERT#1]
I noticed that the `main.py` loaded a `./data/dailydialog/train.h5`. I also downloaded the original `dailydialog` dataset. But I have no idea that how to parse them to `train.h5`.

Could you please give me help?

**Comment by guxd** [comment]
Thanks. I have uploaded the parsed data.

**Comment by eefaan** [comment]
Thanks a lot! @guxd
