### ISSUE TITLE
Data processing

### ISSUE THREAD

**Issue by Lucasftc** [guxd/DialogBERT#10]
Thanks for your great work! I'd like to apply your method and model to a brand new dataset, but have no idea about how to preprocess our dataset to the required  format. Could you release the data preprocessing script?  it'll be of great help!

**Comment by guxd** [comment]
class Index(tables.IsDescription):
    pos_utt = tables.Int32Col() # start offset of an utterance
    res_len = tables.Int32Col() # number of tokens till the end of response
    ctx_len = tables.Int32Col() # number of tokens from the start of dialog 

def binarize(dialogs, tokenizer, output_path):
    """binarize data and save the processed data into a hdf5 file
       :param dialogs: an array of dialogs, 
        each element is a list of <utt> where utt is a array of dialogue utterances. 
    """
    f = tables.open_file(output_path, 'w')
    filters = tables.Filters(complib='blosc', complevel=5)
    arr_contexts = f.create_earray(f.root, 'sentences', tables.Int32Atom(),shape=(0,),filters=filters)
    indices = f.create_table("/", 'indices', Index, "a table of indices and lengths")
    pos_utt = 0
    for i, dialog in enumerate(tqdm(dialogs)):
        n_tokens=0
        ctx_len=0
        for k, (caller, utt, feature) in enumerate(dialog['utts']):
            idx_utt = tokenizer.encode(utt)
            if idx_utt[0]!=tokenizer.cls_token_id: idx_utt = [tokenizer.cls_token_id] + idx_utt
            if idx_utt[-1]!=tokenizer.sep_token_id: idx_utt = idx_utt + [tokenizer.sep_token_id]
            arr_contexts.append(idx_utt)
            n_tokens+=len(idx_utt)
            if k>0: # ignore the first utterance which has no context
                ind = indices.row
                ind['pos_utt'] = pos_utt
                ind['res_len'] = len(idx_utt)
                ind['ctx_len'] = ctx_len   
                ind.append()
            ctx_len+=len(idx_utt)
            pos_utt += len(idx_utt)
        ctx_len=0
    f.close()
