### ISSUE TITLE
DataLoader Function

### ISSUE THREAD

**Issue by dongqian0206** [guxd/DialogBERT#11]
Hi Xiaodong,

Thanks for sharing the source code.

I have a question regarding `data_loader` function. Is there any reason to create mini-batches by adding the following inputs?

`self.cls_utt = [tokenizer.cls_token_id, tokenizer.cls_token_id, tokenizer.sep_token_id]`
`self.sep_utt = [tokenizer.cls_token_id, tokenizer.sep_token_id, tokenizer.sep_token_id]`

The resulting output would be like: `[[101, 101, 102], [contexts], [101, 102, 102]]`.

Best,

Dong

**Comment by guxd** [comment]
Hi Qiandong

Thanks for the question! 
By adding cls_utt and sep_utt, we want to create context-level CLS and SEP vectors for the context BERT. 
So the vector of [101, 101, 102] by the utterance encoder will be serving as the 'CLS' for the context BERT.

**Comment by dongqian0206** [comment]
OK. Got it, thanks!
