### ISSUE TITLE
Could you please share the script for preprocessing the original dialogues?

### ISSUE THREAD

**Issue by frankdarkluo** [guxd/DialogBERT#13]
Hi, I found the code was refreshed 15 days ago.

I would like to use this model for a brand new dialogue dataset. I noticed that the `data/` have h5 files such as `dailydialog/train.h5`. I also downloaded the original dailydialog dataset, but I do not know how to parse them to be `train.h5`.

Could you please share related script or source code please? thank you very much.

**Comment by guxd** [comment]
I have sent it through email.

**Comment by shangeth** [comment]
Hi @guxd ,
I want to train this model on a new dataset, can you kindly share the data processing script?

**Comment by guxd** [comment]
Hi @shangeth , the script has been uploaded to the folder. Please check out `prepare_data.py`.
